extends:
  - stylelint-config-recommended-scss
processors:
  - stylelint-processor-ignore-front-matter
ignoreFiles:
  - 'node_modules/**'
  - '_site/**'
rules:
  no-descending-specificity: null
  rule-empty-line-before:
    - always
    - except:
        - after-single-line-comment
        - first-nested
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
